spring.application.name=loan-service
server.port=8083
spring.data.mongodb.uri=mongodb://localhost:27017/loandb
user.service.url=http://localhost:8081
kyc.service.url=http://localhost:8082


# If using Eureka
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
